-ifndef(CHAT_PROTOCOL_HRL).
-define(CHAT_PROTOCOL_HRL, true).

%% Protocol identifiers shared by the server and client.
-define(PROTO_LOGIN_REQUEST, 1001).
-define(PROTO_LOGIN_RESULT, 1002).
-define(PROTO_CHANNEL_LIST_REQUEST, 2001).
-define(PROTO_CHANNEL_LIST_RESULT, 2002).
-define(PROTO_CHANNEL_JOIN_REQUEST, 2003).
-define(PROTO_CHANNEL_JOIN_RESULT, 2004).
-define(PROTO_CHANNEL_LEAVE_REQUEST, 2005).
-define(PROTO_CHANNEL_LEAVE_RESULT, 2006).
-define(PROTO_CHANNEL_SEND_REQUEST, 2007).
-define(PROTO_CHANNEL_SEND_RESULT, 2008).
-define(PROTO_CHANNEL_PUSH, 2009).
-define(PROTO_CHANNEL_PUSH_BATCH, 2010).
-define(PROTO_PRIVATE_SEND_REQUEST, 3001).
-define(PROTO_PRIVATE_SEND_RESULT, 3002).
-define(PROTO_PRIVATE_PUSH, 3003).
-define(PROTO_MAP_MOVE_REQUEST, 4001).
-define(PROTO_MAP_MOVE_RESULT, 4002).
-define(PROTO_MAP_TELEPORT_REQUEST, 4003).
-define(PROTO_MAP_TELEPORT_RESULT, 4004).
-define(PROTO_NEARBY_SEND_REQUEST, 4005).
-define(PROTO_NEARBY_SEND_RESULT, 4006).
-define(PROTO_NEARBY_PUSH, 4007).
-define(PROTO_ERROR, 9001).

-define(RESULT_SUCCESS, 0).

-define(LOGIN_RESULT_INVALID_LOGIN, 1).
-define(LOGIN_RESULT_ALREADY_ONLINE, 2).

-define(CHANNEL_JOIN_RESULT_INVALID_CHANNEL, 1).
-define(CHANNEL_JOIN_RESULT_ALREADY_JOINED, 2).

-define(CHANNEL_LEAVE_RESULT_INVALID_CHANNEL, 1).
-define(CHANNEL_LEAVE_RESULT_NOT_JOINED, 2).
-define(CHANNEL_LEAVE_RESULT_CANNOT_LEAVE_MAIN, 3).

-define(CHANNEL_SEND_RESULT_INVALID_CHANNEL, 1).
-define(CHANNEL_SEND_RESULT_NOT_JOINED, 2).
-define(CHANNEL_SEND_RESULT_BROADCAST_FAILED, 3).

-define(PRIVATE_SEND_RESULT_TARGET_OFFLINE, 1).

-define(MAP_MOVE_RESULT_INVALID_DIRECTION, 1).
-define(MAP_MOVE_RESULT_OUT_OF_BOUNDS, 2).

-define(MAP_TELEPORT_RESULT_INVALID_POSITION, 1).

-define(MAP_DIRECTION_UP, 1).
-define(MAP_DIRECTION_DOWN, 2).
-define(MAP_DIRECTION_LEFT, 3).
-define(MAP_DIRECTION_RIGHT, 4).

-define(ERROR_NOT_LOGGED_IN, 1).
-define(ERROR_INVALID_PACKET, 2).
-define(ERROR_UNKNOWN_PROTO, 3).

-define(CHANNEL_TYPE_MAIN, 1).
-define(CHANNEL_TYPE_PUBLIC, 2).

-endif.
