-ifndef(CHAT_PROTOCOL_HRL).
-define(CHAT_PROTOCOL_HRL, true).

%% Protocol identifiers shared by the server and client.
-define(PROTO_LOGIN_REQUEST, 1001).
-define(PROTO_LOGIN_RESULT, 1002).
-define(PROTO_CHANNEL_LIST_REQUEST, 2001).
-define(PROTO_CHANNEL_LIST_RESULT, 2002).
-define(PROTO_CHANNEL_JOIN_REQUEST, 2003).
-define(PROTO_CHANNEL_JOIN_RESULT, 2004).
-define(PROTO_CHANNEL_LEAVE_REQUEST, 2005).
-define(PROTO_CHANNEL_LEAVE_RESULT, 2006).
-define(PROTO_CHANNEL_SEND_REQUEST, 2007).
-define(PROTO_CHANNEL_SEND_RESULT, 2008).
-define(PROTO_CHANNEL_PUSH, 2009).
-define(PROTO_PRIVATE_SEND_REQUEST, 3001).
-define(PROTO_PRIVATE_SEND_RESULT, 3002).
-define(PROTO_PRIVATE_PUSH, 3003).
-define(PROTO_ERROR, 9001).

-define(RESULT_SUCCESS, 0).

-define(CHANNEL_TYPE_MAIN, 1).
-define(CHANNEL_TYPE_PUBLIC, 2).

-endif.
